build:
  commands:
    - mvn clean package -DskipTests

    - echo "Building product-service image..."
    - docker build -t $DOCKER_USERNAME/product-service:latest ./product-service

    - echo "Building user-order-service image..."
    - docker build -t $DOCKER_USERNAME/user-order-service:latest ./user-order-service

post_build:
  commands:
    - docker push $DOCKER_USERNAME/product-service:latest
    - docker push $DOCKER_USERNAME/user-order-service:latest