version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  build:
    commands:
      - echo "Building application..."
      - mvn package -DskipTests
      - cp target/*.jar app.jar

artifacts:
  files:
    - app.jar