version: 0.2

phases:
  build:
    commands:
      - set -x
      - echo "Waiting for app to start..."
      - sleep 30

      - echo "Running smoke tests..."
      - curl -v -f http://$APP_URL/actuator/health