CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,

    status VARCHAR(50) NOT NULL,

    shipping_name VARCHAR(255),
    shipping_street VARCHAR(255),
    shipping_city VARCHAR(255),
    shipping_postal_code VARCHAR(50),
    shipping_country VARCHAR(100),

    ordered_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE order_items (
    order_id BIGINT NOT NULL,

    product_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    price DECIMAL(19,2) NOT NULL,
    image VARCHAR(500) NOT NULL,
    quantity INT NOT NULL,

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders(id)
        ON DELETE CASCADE,

    CONSTRAINT pk_order_items PRIMARY KEY (order_id, product_id)
);


CREATE INDEX idx_orders_user_id ON orders(user_id);

ALTER TABLE orders
    ADD CONSTRAINT chk_orders_status
        CHECK (status IN ('PENDING', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED'));